### ISSUE TITLE
Thống nhất ý tưởng & requirements

### ISSUE THREAD

**Issue by danhmanh** [danhmanh/se02-vnu-student#1]
Ý tưởng ban đầu sẽ là xây dựng 1 trang web cho sinh viên trường Đại học Quốc gia Hà Nội có thể dễ dàng theo dõi được điểm số của mình từ [trang đào tạo của trường](https://daotao.vnu.edu.vn)

- Tự động crawl dữ liệu từ trang đào tạo và fetch vào trang web, xây dựng các tính năng xoay quanh nguồn dữ liệu này
- Sắp xếp thời khóa biểu
- Tổng hợp kết quả học tập
- ...

Mọi người có ý kiến gì thêm hãy để lại bình luận ạ.

**Comment by hwanngo** [comment]
- Sinh viên có thể báo cáo cho phòng đào tạo khi kết quả học tập bị sai sót không?

**Comment by danhmanh** [comment]
> * Sinh viên có thể báo cáo cho phòng đào tạo khi kết quả học tập bị sai sót không?

mình sẽ dự định thông báo bằng đường nào ?

**Comment by hwanngo** [comment]
> mình sẽ dự định thông báo bằng đường nào ?

Có thể đi qua đường email không? Ví dụ như thêm nút "Ý kiến/Báo cáo sai sót"?
Sau khi nhấn thì nó sẽ hiện ra một pop-up với người nhận là mail của phòng đào tạo (tiêu đề có thể set mặc định là "[Mã sinh viên] - Báo cáo sai sót bảng điểm" nếu được), nội dung mail sinh viên tự gõ.

**Comment by danhmanh** [comment]
> > > * Sinh viên có thể báo cáo cho phòng đào tạo khi kết quả học tập bị sai sót không?
> > 
> > 
> > mình sẽ dự định thông báo bằng đường nào ?
> 
> Có thể đi qua đường email không? Ví dụ như thêm nút "Ý kiến/Báo cáo sai sót"?
> Sau khi nhấn thì nó sẽ hiện ra một pop-up với người nhận là mail của phòng đào tạo (tiêu đề có thể set mặc định là [Mã sinh viên] - Báo cáo sai sót bảng điểm nếu được), nội dung mail sinh viên tự gõ.

Phương án này là hoàn toàn khả thi, có thể đi kèm cả screenshot đính kèm vào mail để làm bằng chứng. Hãy thêm vào issues tính năng này.

**Comment by dangxuanphuc** [comment]
Khi sinh viên quên pass + mất tài khoản mail hus thì có thể thông báo cho bên phòng đào tạo để lấy lại tài khoản được không?

**Comment by hwanngo** [comment]
> Khi sinh viên quên pass + mất tài khoản mail hus thì có thể thông báo cho bên phòng đào tạo để lấy lại tài khoản được không?

Có thể làm được với tính năng gửi mail tôi đã đề xuất ở trên, thay vì tiêu đề "Báo cáo sai sót bảng điểm" ta sẽ ghi "Xin cấp lại tài khoản/mật khẩu"

**Comment by dangxuanphuc** [comment]
> > Khi sinh viên quên pass + mất tài khoản mail hus thì có thể thông báo cho bên phòng đào tạo để lấy lại tài khoản được không?
> 
> Có thể làm được với tính năng gửi mail tôi đã đề xuất ở trên, thay vì tiêu đề "Báo cáo sai sót bảng điểm" ta sẽ ghi "Xin cấp lại tài khoản/mật khẩu"

À thực ra ko cần gửi cho bên PĐT mà chỉ là gửi mail lấy lại mật khẩu thông thường thôi. Email cá nhân đã được lưu trong hồ sơ.
