### ISSUE TITLE
Trang dangkihoc đã xoá mất lịch học cũ

### ISSUE THREAD

**Issue by danhmanh** [danhmanh/se02-vnu-student#15]
Như tiêu đề thì trang `http://dangkyhoc.vnu.edu.vn/xem-va-in-ket-qua-dang-ky-hoc/1?layout=main` đã xoá mất danh sách đăng kí môn. Chúng ta sẽ không thể crawl thông tin ở đây nữa. Khá buồn.

**Comment by hwanngo** [comment]
15h ngày 11/12 sẽ mở đăng ký tín chỉ kỳ 2 năm 2018-2019, tôi nghĩ là chiều nay đăng ký xong chúng ta có thể kiểm tra lại 😑

**Comment by danhmanh** [comment]
@conghoan0604 hi vọng là thế
