### ISSUE TITLE
Chat theo thời gian thực

### ISSUE THREAD

**Issue by dangxuanphuc** [danhmanh/se02-vnu-student#19]
Chúng ta sẽ tạo ra một tính năng giúp sinh viên có thể dễ dàng trao đổi thông tin về các môn học ngay trên ứng dụng mà không phải sử dụng Facebook Messenger,...

**Comment by danhmanh** [comment]
Tính năng này khá hay, nếu web có thêm tính năng này thì khá là tốt. +1.
