### ISSUE TITLE
Thống nhất công nghệ sử dụng

### ISSUE THREAD

**Issue by danhmanh** [danhmanh/se02-vnu-student#2]
Hiện tại thì nhóm chúng ta có 3 người đều biết về Rails nên sẽ chọn Ruby on Rails là framework để thực hiện project này nhé.
Phần còn lại là xác định trước các ```gem``` sẽ dùng trong project để đọc doc trước, hiểu hơn về cách sử dụng và ứng dụng của ```gem``` 
Mọi người để lại ý kiến phía dưới nhé.

**Comment by hwanngo** [comment]
VNU có cả sinh viên Việt Nam lẫn sinh viên nước ngoài nên là có thể sẽ cần đến tính năng chuyển đổi ngôn ngữ. Có thể dùng gem `i18n` thuần hoặc nếu định sử dụng javascript thì dùng gem `i18n-js` nhé.

**Comment by danhmanh** [comment]
vấn đề quan trọng nhất ở đây là việc cào dữ liệu từ trang đào tạo của trường. Có thể cân nhắc giữa `mechanize`, `nokogiri` hoặc `capybara`.

**Comment by dangxuanphuc** [comment]
t thấy bây giờ khá nhiều người dùng `nokogiri` thì nó phải có ưu điểm hơn những gem khác. Chúng ta có thể dùng nó.

**Comment by danhmanh** [comment]
OK close. Bước tiếp theo là sẽ init project và mọi người pull về nhé.
