### ISSUE TITLE
Tập hợp sinh viên vào Group môn học

### ISSUE THREAD

**Issue by danhmanh** [danhmanh/se02-vnu-student#20]
- Khi sinh viên đăng kí môn học thành công, các sinh viên học cùng môn học sẽ được tập hợp vào 1 group để dễ dàng trao đổi thông tin, không cần phải mò mẫm tìm nhau nữa.

**Comment by dangxuanphuc** [comment]
Một tính năng rất hay giúp sinh viên có thể sử dụng như 1 mạng xã hội

**Comment by danhmanh** [comment]
#25
