### ISSUE TITLE
Lỗi cài đặt Gem / Bundle

### ISSUE THREAD

**Issue by danhmanh** [danhmanh/se02-vnu-student#23]
![image](https://user-images.githubusercontent.com/32545300/50756834-147f7a00-1290-11e9-9a2b-f421f7e9abeb.png)

**Comment by dangxuanphuc** [comment]
Có vẻ là do version bundler rồi. Ông thử sửa version bundler trong `Gemfile.lock` xem được không.

**Comment by hwanngo** [comment]
Ông thử remove `Gemfile.lock` rồi chạy `bundle` cho nó generate ra clean file xem nào...
Kiểm tra lại version của `gem` ông định thêm vào xem có compatible không...

**Comment by danhmanh** [comment]
bỏ gem *fog* là lại bundle được. Không hiểu sao, Đã update bundler rồi
