### ISSUE TITLE
Thêm avatar vào root_path

### ISSUE THREAD

**Issue by danhmanh** [danhmanh/se02-vnu-student#26]
![image](https://user-images.githubusercontent.com/32545300/50901204-0b3a0d00-144a-11e9-8e4c-7aa059a0f06e.png)
phần này cần cho thêm avatar của current_user vào nữa, nhìn nó hơi trống

**Comment by hwanngo** [comment]
https://github.com/danhmanh/se02-vnu-student/pull/27
