### ISSUE TITLE
Update README.md theo đúng yêu cầu

### ISSUE THREAD

**Issue by danhmanh** [danhmanh/se02-vnu-student#4]
Chúng ta cần update `README.md` để mô tả công việc đang làm, công nghệ đang dùng và mô tả cách sử dụng. Any idea ?

**Comment by dangxuanphuc** [comment]
Cần mô tả công nghệ, công dụng với cách sử dụng thôi chứ công việc đang và sẽ làm thì nó trong Product Backlog rồi mà.

**Comment by hwanngo** [comment]
Không cần thiết ghi công nghệ đang dùng vì GitHub hỗ trợ sẵn phần phân biệt ngôn ngữ rồi nhé.
Phần mô tả thì trong issue hôm trước ta bàn về tính năng gì thì ghi nó ra.
Phần cách sử dụng mình đồng ý với 2 bạn.
![screenshot_1](https://user-images.githubusercontent.com/40811995/47927358-a6b47c00-def5-11e8-94f3-0701781806fa.png)
