### ISSUE TITLE
Phân tích thiết kế Database

### ISSUE THREAD

**Issue by dangxuanphuc** [danhmanh/se02-vnu-student#5]

**Comment by danhmanh** [comment]
https://cacoo.com/diagrams/nYbwKyOoKOQyuVz3/A81DF
![image](https://user-images.githubusercontent.com/32545300/47973992-e89e1780-e0d9-11e8-80a6-8ed0f4619dd7.png)
Trước hết thì db thế này đã nhé. Cần họp 1 buổi trao đổi thêm.

**Comment by dangxuanphuc** [comment]
student có thể tạo post à

**Comment by danhmanh** [comment]
@dangxuanphuc uhm, student có thể tạo post, ở đây student đóng vai trò như một user bình thường
